## More Operations on Matrices and Vectors

- For multiplication, you have to make sure the col dimension is equal to the row dimension of the other matrix 
- a transpose can also work, still depending on the dimension
- for subtraction, you have to make sure its a square matrix on both sides or the matrices have the same dimension 
- we call a matrix whose determinant is 0 a singular matrix because its inverse would not exist

In [1]:
import numpy as np
import sympy as sy

In [3]:
L = sy.Matrix([[12,4,6,2],[23,4,5,6],[2.5,2,5,1]])
M = sy.Matrix([[12,14,26,22],[23,42,51,62],[12,25,32,5.1]])
N = sy.Matrix([[12,4],[23,4],[2.5,2]])
P = sy.Matrix([[12,4,22],[23,4,0.5],[2.5,2,8]])


In [4]:
L,M,N,P

(Matrix([
 [ 12, 4, 6, 2],
 [ 23, 4, 5, 6],
 [2.5, 2, 5, 1]]),
 Matrix([
 [12, 14, 26,  22],
 [23, 42, 51,  62],
 [12, 25, 32, 5.1]]),
 Matrix([
 [ 12, 4],
 [ 23, 4],
 [2.5, 2]]),
 Matrix([
 [ 12, 4,  22],
 [ 23, 4, 0.5],
 [2.5, 2,   8]]))

In [109]:
N.T * P

Matrix([
[679.25, 145.0, 295.5],
[ 145.0,    36, 106.0]])

In [16]:
P*L

Matrix([
[ 291.0,   108,   202,   70],
[369.25, 109.0, 160.5, 70.5],
[  96.0,  34.0,  65.0, 25.0]])

In [28]:
K = P*M
K

Matrix([
[  500,   886,  1220,  624.2],
[374.0, 502.5, 818.0, 756.55],
[172.0, 319.0, 423.0,  219.8]])

In [29]:
K.T

Matrix([
[  500,  374.0, 172.0],
[  886,  502.5, 319.0],
[ 1220,  818.0, 423.0],
[624.2, 756.55, 219.8]])

#### because of the shape rule, only P can be used to multiply any of this matrix 

## Finding Transpose of a Matrix

In [23]:
G= np.array([[-1,2,-12,4],[23,-5,6,2]])
I = sy.eye(3) # identity matrix
I

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [30]:
I.transpose()

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [32]:
G

array([[ -1,   2, -12,   4],
       [ 23,  -5,   6,   2]])

In [34]:
G.transpose()

array([[ -1,  23],
       [  2,  -5],
       [-12,   6],
       [  4,   2]])

In [35]:
M

Matrix([
[12, 14, 26,  22],
[23, 42, 51,  62],
[12, 25, 32, 5.1]])

In [36]:
M.T

Matrix([
[12, 23,  12],
[14, 42,  25],
[26, 51,  32],
[22, 62, 5.1]])

* # Determinants
 - you can use .det from sympy or linalg.det from numpy, 
 - matrix must be sqaure i.e same number of columns and rows

In [38]:
P.det()

433.000000000000

In [39]:
J = np.array([[-1,2,],[23,-5]])

In [41]:
np.linalg.det(J)

-41.00000000000001

* ## Getting the inverse of a matrix
 - for a matrix to have an inverse, the determinant has to be 0 and a square matrix

In [42]:
# create a random matrix using np.random
rand_matrix = np.random.randint(-8,5, size =(5,5))

In [43]:
rand_matrix

array([[ 0, -5, -6, -4, -2],
       [-2,  2, -8, -8, -4],
       [-4,  2, -7, -3,  2],
       [ 2, -1,  3, -4,  1],
       [-7, -2, -2, -5, -1]])

In [51]:
v = np.linalg.inv(rand_matrix)

### we can use sy.matrix to change our ragged looging numpy array to a beautiful looking sympy matrix

In [110]:
sy.Matrix(v)

Matrix([
[ 0.0470051034112275,   0.0244426537738383, -0.0024174053182917,   0.0674187483212463,  -0.129196884233145],
[ -0.136717700778942,   0.0889067955949503,   0.024174053182917, -0.00752081654579641, -0.0413644910018802],
[-0.0663443459575611, -0.00449905989793178, -0.0737308622078969,   0.0562718237980124,   0.059495030889068],
[ 0.0120870265914585,  -0.0437147461724416, -0.0149073327961322,   -0.139806607574537, -0.0189363416599517],
[ 0.0166532366371206,   -0.121340316948697,   0.190572119258662,    0.129599785119527, -0.0372011818426001]])

In [98]:
r_matrix = sy.Matrix(np.random.randint(-4,9, size =(4,4)))

In [99]:
r_matrix

Matrix([
[-2, -1, -2,  4],
[-4,  1, -1, -4],
[-3, -4, -4,  2],
[ 8, -4,  1,  1]])

In [100]:
r_matrix.inv()

Matrix([
[  26/17,   22/17, -15/17,  14/17],
[  37/17,   30/17, -22/17,  16/17],
[-173/51, -149/51,  30/17, -28/17],
[  -7/51,  -19/51,   2/17,  -3/17]])

In [140]:
po = sy.diag(1,2,5,8,5,9)

In [141]:
po

Matrix([
[1, 0, 0, 0, 0, 0],
[0, 2, 0, 0, 0, 0],
[0, 0, 5, 0, 0, 0],
[0, 0, 0, 8, 0, 0],
[0, 0, 0, 0, 5, 0],
[0, 0, 0, 0, 0, 9]])

In [120]:
po.inv().T

Matrix([
[1,   0,   0,   0,   0],
[0, 1/2,   0,   0,   0],
[0,   0, 1/5,   0,   0],
[0,   0,   0, 1/8,   0],
[0,   0,   0,   0, 1/5]])

In [55]:
pk = sy.diag([1,2,3])

In [72]:
gk = sy.eye(9)

In [73]:
gk

Matrix([
[1, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [74]:
gk.inv()

Matrix([
[1, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 1, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [77]:
two_by_3 = sy.Matrix(np.random.randint(-2,4, size = (2,3)))

In [78]:
two_by_3

Matrix([
[1, 0, 2],
[2, 3, 3]])

In [79]:
four_by_2 = sy.Matrix(np.random.randint(-9,4, size = (4,3)))
four_by_2

Matrix([
[-9, -1,  3],
[-1, -3, -1],
[-8,  3, -2],
[-4, -3, -1]])

### these matrices cant be subtracted cause they arent of the same dimension

In [81]:
a = sy.Matrix([[1,-1], [2,2]])
b = sy.Matrix([[2,0],[0,-1]])

a, b

(Matrix([
 [1, -1],
 [2,  2]]),
 Matrix([
 [2,  0],
 [0, -1]]))

In [84]:
a1 = a.inv()

In [85]:
b1 = b.inv()

In [86]:
a1*b1

Matrix([
[ 1/4, -1/4],
[-1/4, -1/4]])

## More Matrix Algebra 

In [87]:
import random

In [91]:
L1 = np.linspace(-3,9,9)
L1
# linspace returns evenly spaced number and includes the upper bound but random.randint would not include the upper bound

array([-3. , -1.5,  0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. ])

In [93]:
L1.shape

(9,)

In [101]:
M1 = L1.reshape(3,3) # seems you can reshape into the multiple of the actual shape

In [102]:
M1

array([[-3. , -1.5,  0. ],
       [ 1.5,  3. ,  4.5],
       [ 6. ,  7.5,  9. ]])

In [103]:
T1 = np.random.randint(-2,8, size=(3,3))
T1

array([[ 5,  1, -1],
       [-2, -1,  3],
       [ 0,  4,  3]])

## we can also use the matmul method to multiply two matrices 
- the dot method can be used too
- you can also use the @ symbol

In [105]:
np.matmul(M1,T1)

array([[-12. ,  -1.5,  -1.5],
       [  1.5,  16.5,  21. ],
       [ 15. ,  34.5,  43.5]])

In [106]:
M1*T1

array([[-15. ,  -1.5,  -0. ],
       [ -3. ,  -3. ,  13.5],
       [  0. ,  30. ,  27. ]])

#### when we tried using the traditional star method from python it gave us a wrong answer

In [107]:
M1.dot(T1)

array([[-12. ,  -1.5,  -1.5],
       [  1.5,  16.5,  21. ],
       [ 15. ,  34.5,  43.5]])

In [108]:
M1@T1

array([[-12. ,  -1.5,  -1.5],
       [  1.5,  16.5,  21. ],
       [ 15. ,  34.5,  43.5]])

## DIAGONALIZATION OF A MATRIX

In [121]:
from sympy import *

In [129]:
M = Matrix([[-2,4,2], [3,-2,4],[2,-4,3]])

In [130]:
M

Matrix([
[-2,  4, 2],
[ 3, -2, 4],
[ 2, -4, 3]])

In [142]:
P,D = M.diagonalize()

In [143]:
P

Matrix([
[    (-600*(1 + sqrt(3)*I)*(6*sqrt(8814) + 577)**(2/3) + 6*(1 + sqrt(3)*I)**2*(2 - (1 + sqrt(3)*I)*(6*sqrt(8814) + 577)**(1/3))*(6*sqrt(8814) + 577) - (100 + (-2 + (1 + sqrt(3)*I)*(6*sqrt(8814) + 577)**(1/3))*(1 + sqrt(3)*I)*(6*sqrt(8814) + 577)**(1/3))**2*(6*sqrt(8814) + 577)**(1/3))/(288*(1 + sqrt(3)*I)**2*(6*sqrt(8814) + 577)),     ((-1 + sqrt(3)*I)*(100 + (-2 + (1 - sqrt(3)*I)*(6*sqrt(8814) + 577)**(1/3))*(1 - sqrt(3)*I)*(6*sqrt(8814) + 577)**(1/3))**2*(6*sqrt(8814) + 577)**(1/3) + 6*(1 - sqrt(3)*I)**3*(2 + (-1 + sqrt(3)*I)*(6*sqrt(8814) + 577)**(1/3))*(6*sqrt(8814) + 577) - 600*(1 - sqrt(3)*I)**2*(6*sqrt(8814) + 577)**(2/3))/(288*(1 - sqrt(3)*I)**3*(6*sqrt(8814) + 577)),       -23*(6*sqrt(8814) + 577)**(1/3)/75 - sqrt(8814)*(6*sqrt(8814) + 577)**(2/3)/7500 - 2/3 - 2*(6*sqrt(8814) + 577)**(2/3)/1875 + sqrt(8814)*(6*sqrt(8814) + 577)**(1/3)/300],
[(-3000*(1 + sqrt(3)*I)*(6*sqrt(8814) + 577)**(2/3) - (100 + (-2 + (1 + sqrt(3)*I)*(6*sqrt(8814) + 577)**(1/3))*(1 + sqrt(3)*I)*(

In [144]:
D

Matrix([
[-1/3 - 25/(3*(-1/2 - sqrt(3)*I/2)*(6*sqrt(8814) + 577)**(1/3)) - (-1/2 - sqrt(3)*I/2)*(6*sqrt(8814) + 577)**(1/3)/3,                                                                                                                   0,                                                                         0],
[                                                                                                                  0, -1/3 - (-1/2 + sqrt(3)*I/2)*(6*sqrt(8814) + 577)**(1/3)/3 - 25/(3*(-1/2 + sqrt(3)*I/2)*(6*sqrt(8814) + 577)**(1/3)),                                                                         0],
[                                                                                                                  0,                                                                                                                   0, -(6*sqrt(8814) + 577)**(1/3)/3 - 25/(3*(6*sqrt(8814) + 577)**(1/3)) - 1/3]])

In [138]:
k = M.eigenvects

In [139]:
k

<bound method MatrixEigen.eigenvects of Matrix([
[-2,  4, 2],
[ 3, -2, 4],
[ 2, -4, 3]])>